apiVersion: v2
name: pagopa-afm-fee-reporting-cronjob
description: Microservice that handle the creation of json report about the fees applied by PSPs
version: 1.0.0
dependencies:
  - name: cron-chart
    version: 1.19.0 # verificare
    repository: "https://pagopa.github.io/aks-cron-chart-blueprint"

